# Generated by Django 4.0.3 on 2022-03-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
